sudo: false


jobs:
    include:
        - stage: test
          name: "symfony"
          language: php
          cache:
              directories:
                  - $HOME/.composer/cache/files
                  - symfony/vendor
          services:
              - mysql
          php:
              - 7.2
              - 7.3
          before_install:
              - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then phpenv config-rm xdebug.ini; fi;'
              - composer self-update
              - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update -d symfony "symfony/symfony:${SYMFONY_VERSION}"; fi;

          install:
              - COMPOSER_MEMORY_LIMIT=-1 composer update ${COMPOSER_FLAGS} --prefer-source -d symfony

          before_script:
              - mysql -u root -e "drop database if exists mydatabase;"
              - mysql -u root -e "create database mydatabase;"
              - mysql -u root -e "grant all privileges on mydatabase.* to 'devuser' identified by 'devpass'; flush privileges;"

          script:
              - symfony/app/console propel:migration:migrate
              - symfony/app/console propel:fixtures:load
              - symfony/bin/phpunit --colors -c symfony/app

        - stage: test
          name: "angular test"
          language: node_js
          node_js:
              - "10"
          script:
              - npm run affected:test --prefix angular -- --all

        - stage: build
          name: "angular build"
          language: node_js
          node_js:
              - "10"
          script:
              - npm run build --prefix angular -- --aot

        - stage: deploy
          language: bash
          name: "Deploy"
          script:
              - echo Deploy
