source "https://supermarket.chef.io"

metadata

cookbook "apache2", "~> 4.0.0"
cookbook "apt", "~> 6.0.0"
cookbook "database"
cookbook "mariadb", "1.5.3"
cookbook "mysql2_chef_gem"
cookbook "postgresql", "~> 6.0.0"
cookbook "selinux_policy", "=2.0.1"
cookbook "seven_zip", "~> 2.0.0"
cookbook "windows", "~> 4.0.0"
cookbook "yum", "~> 5.0.0"
cookbook "mingw", "=2.1.0"
cookbook "yum-epel", "~> 2.0.0"
