source "https://supermarket.chef.io"

metadata

cookbook "apache2", "~> 4"
cookbook "apt", "~> 6"
cookbook "database"
cookbook "mariadb", "1.5.3"
cookbook "mysql2_chef_gem"
cookbook "postgresql", "~> 6"
cookbook "selinux_policy", "=2.0.1"
cookbook "seven_zip", "~> 2"
cookbook "windows", "~> 4"
cookbook "yum", "~> 5"
cookbook "mingw", "~> 2.1.1"
cookbook "yum-epel", "~> 4"
cookbook "composer"
cookbook "php", "~> 6"